### PR TITLE
E501 open bracket

### PR DESCRIPTION
**Pull request by tobixx**
solves #281 

but I have no clue what travis is complaining about - seems not to be related.

### CODE REVIEW

**Comment by spaceone** [comment]
The tests are failing because https://github.com/tobixx/autopep8/blob/e501_open_bracket/autopep8.py#L516 
```
                        print(
                            '--->  Not fixing {f} on line {l}'.format(
                                f=result['id'], l=result['line']),
file=sys.stderr)
```
l is detected as variable on pypy.

```
$ if [ "$TRAVIS_PYTHON_VERSION" != "pypy"* ]; then pycodestyle autopep8.py; fi

autopep8.py:184:1: E305 expected 2 blank lines after class or function definition, found 0

autopep8.py:371:1: E305 expected 2 blank lines after class or function definition, found 0

autopep8.py:516:49: E741 ambiguous variable name 'l'

autopep8.py:1537:1: E305 expected 2 blank lines after class or function definition, found 1

autopep8.py:3732:1: E305 expected 2 blank lines after class or function definition, found 1

The command "if [ "$TRAVIS_PYTHON_VERSION" != "pypy"* ]; then pycodestyle autopep8.py; fi" exited with 1.
```

So you can ignore this. It's a bug in pycodestyle on pypy.

**Comment by tobixx** [comment]
Thanks @spaceone - that's what I wanted to hear ;-)

**Comment by myint** [comment]
@spaceone, pypy is not why the tests are failing. It looks like pycodestyle has a new warning about `l` being ambiguous and warning that it could be interpreted as the number 1. I've fixed this is 084e18dccaed82ba1630bffc3baa08b3213dd4c4.

**Comment by myint** [comment]
Thanks.

**Pull request merged**
