### PR TITLE
E301 has been further split into E305, E306

### PR DESCRIPTION
**Pull request by spaceone**
Adjust to API changes in pycodestyle 2.1; Issue #274

### CODE REVIEW

**Comment by myint** [comment]
Thanks.

**Comment by myint** [comment]
I had to revert this. It seems to be causing test failures.

**Comment by spaceone** [comment]
Can you please tell me which failures? I can only see https://travis-ci.org/hhatto/autopep8/jobs/174259232. 
```
The command "eval git fetch origin +refs/pull/286/merge:" failed. Retrying, 2 of 3.

fatal: Couldn't find remote ref refs/pull/286/merge
```

This might be caused because I removed my branch after you merged this.

**Comment by myint** [comment]
https://travis-ci.org/hhatto/autopep8/jobs/173794811#L214
https://travis-ci.org/hhatto/autopep8/jobs/173794811#L1663

**Comment by spaceone** [comment]
And these fixed are caused by that commit? Or are they because of further API changes of pycodestyle?

**Comment by myint** [comment]
Yes, they are caused by that commit. It looks like you need to update the expected test output.

**Pull request merged**
