### PR TITLE
Support E713 in more cases

### PR DESCRIPTION
**Pull request by mbanders**
Updated test cases as well.

### CODE REVIEW

**Comment by myint** [comment]
This seems too dangerous to me. I would rather not merge it.

For example the following gets scrambled.

```python
if not x in foo and y not in zoo:
    pass
```

```diff
--- original/foo.py
+++ fixed/foo.py
@@ -1,2 +1,2 @@
-if not x in foo and y not in zoo:
+if x in foo and y not not in zoo:
     pass
```

**Comment by mbanders** [comment]
I could change the "if re.match" to only match if there is one " in " and not match if there are more.

**Comment by myint** [comment]
I think I would rather play it safe and leave things as is. I think the AST (as used in `lib2to3` and `python-modernize`) is needed to properly handle this case.

**Comment by mbanders** [comment]
I suppose, perhaps also autopep8 shouldn't include E713 in the list of things it can fix.

**Comment by myint** [comment]
Or maybe add some kind of caveat. (Actually, several of the fixes have such caveats. For example, if long line is composed of just a single long string, autopep8 will not touch it.)

**Pull request closed without merging**
